### PR TITLE
drafted partnership agreement & added CfA as an example

### PR DESCRIPTION
**Pull request by sawks**
I've put together a template for the agreements with supporting orgs and dropped in Code for Australia's as an example to reference.

Would appreciate your input on how it reads for clarity, any additional responsibilities we should cover as a default and example cases that might not fit.

### CODE REVIEW

**Review by dominikwilkowski — APPROVED** [review]
Looks great

**Review by elisechant — COMMENTED** [review]
This is excellent 👏 

Where do we agree to include the Partner's logo? cc @dominikwilkowski.

**Comment by elisechant** [comment]
@sawks shall we include a date period?

**Comment by sawks** [comment]
> @sawks shall we include a date period?

good shout - maybe just a commencement date for the agreement and TSC can use that to check in on a recurring basis

**Pull request merged**
